update nu crates to 0.90.1
abusch/nu_plugin_semver pull request #1
Opened 2024-02-07 17:27 UTC by Inveracity

This PR updates the nu crates to recently released 0.90.1

also, I've never written a single line of Rust until just now with this PR, so I have no clue if these changes are correct. But it compiles and the plugin seems to work, at least for sorting version numbers 🤞

2024-02-07 22:56 UTC, abusch requested changes
Thanks for the PR! I've left a couple of comments about flag handling, but otherwise it looks good!

2024-02-07 22:56 UTC, abusch commented on src/plugin.rs
> -                if ignore_errors {
I think you instead need to do "throw" the error when getting the flag by doing `let ignore_errors = call.has_flag("ignore-errors")?;` above (note the `?` at the end), and then keep using the boolean here as before.

2024-02-07 22:56 UTC, abusch commented on src/plugin.rs
> +        if reverse.is_ok() {
Same here.

2024-02-08 07:45 UTC, Inveracity commented on src/plugin.rs
> -                if ignore_errors {
ah, that's a cool language feature. I've updated the code, I hope it's right. Thank you!

2024-02-08 20:29 UTC, merged